[window]
opacity = 0.95

[colors]
draw_bold_text_with_bright_colors = false

[font]
size = 12.5

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[window.class]
general = "Alacritty"
instance = "Alacritty"
